# Generated by Django 3.0.8 on 2020-08-17 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('teachingstaff', 'teachingstaff'), ('nonteachingstaff', 'nonteachingstaff'), ('supervisor', 'supervisor'), ('viceprincipal', 'viceprincipal'), ('principal', 'principal')], max_length=50, verbose_name='Types')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupervisorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Sick Leave Available Days')),
                ('annualleave', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Annual Leave Available Days')),
                ('firstday', models.DateField(default=datetime.datetime(2020, 8, 17, 9, 41, 19, 571099, tzinfo=utc))),
                ('is_supervisor', models.BooleanField(default=True, verbose_name='Supervisor status')),
                ('overseeing', models.ManyToManyField(related_name='overseeing', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorDetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachertimeofftype', models.CharField(choices=[('SL', 'Sick Leave'), ('OL', 'Official Leave'), ('CL', 'Casual Leave'), ('TB', 'Special Tuberculosis Leave'), ('ML', 'Maternal Leave'), ('PL', 'Paternity Leave'), ('ST', 'Study Leave'), ('JK', 'Jurors or Witnesses'), ('LS', 'Leave for Special Events'), ('O', 'Others')], default='SL', max_length=10, verbose_name='Teacher Type of Leave')),
                ('nonteachertimeofftype', models.CharField(choices=[('SL', 'Sick Leave'), ('OL', 'Official Leave'), ('AL', 'Annual Leave'), ('OT', 'Over Time'), ('TB', 'Special Tuberculosis Leave'), ('ML', 'Maternal Leave'), ('PL', 'Paternity Leave'), ('JK', 'Jurors or Witnesses'), ('O', 'Others')], default='SL', max_length=10, verbose_name='Non Teacher Type of Leave')),
                ('startdate', models.DateTimeField(default=datetime.datetime(2020, 8, 17, 9, 41, 19, 572254, tzinfo=utc))),
                ('enddate', models.DateTimeField(default=datetime.datetime(2020, 8, 17, 9, 41, 19, 572281, tzinfo=utc))),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('reason', models.CharField(default='', max_length=200)),
                ('firststatus', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Denied', 'denied')], default='Pending', max_length=10)),
                ('firstcomment', models.CharField(blank=True, max_length=200)),
                ('finalstatus', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Denied', 'denied')], default='Pending', max_length=10)),
                ('finalcomment', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customstaff.user',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customstaff.user',),
        ),
        migrations.CreateModel(
            name='TeachingStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customstaff.user',),
        ),
        migrations.CreateModel(
            name='TeachingStaffDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Sick Leave Available Days')),
                ('casualleave', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Casual Leave Available Days')),
                ('firstday', models.DateField(default=datetime.datetime(2020, 8, 17, 9, 41, 19, 569848, tzinfo=utc))),
                ('is_teacher', models.BooleanField(default=True, verbose_name='teacher status')),
                ('is_viceprincipal', models.BooleanField(default=False, verbose_name='Viceprincipal status')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Principal status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customstaff.TeachingStaff')),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingStaffDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Sick Leave Available Days')),
                ('annualleave', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Annual Leave Available Days')),
                ('firstday', models.DateField(default=datetime.datetime(2020, 8, 17, 9, 41, 19, 570550, tzinfo=utc))),
                ('is_nonteacher', models.BooleanField(default=True, verbose_name='Non teaching staff status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customstaff.NonTeachingStaff')),
            ],
        ),
    ]
