# Generated by Django 3.0.8 on 2020-08-11 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('teachingstaff', 'teachingstaff'), ('nonteachingstaff', 'nonteachingstaff')], default='teachingstaff', max_length=50, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeofftype', models.CharField(choices=[('SL', 'sick leave'), ('OL', 'official leave'), ('CL', 'casual leave'), ('AL', 'annual leave')], default='SL', max_length=10)),
                ('startdate', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 9, 16, 6, 466193, tzinfo=utc))),
                ('enddate', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 9, 16, 6, 466227, tzinfo=utc))),
                ('reason', models.CharField(default='', max_length=200)),
                ('firststatus', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=10)),
                ('firstcomment', models.CharField(default='', max_length=200)),
                ('finalstatus', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=10)),
                ('finalcomment', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customstaff.user',),
        ),
        migrations.CreateModel(
            name='TeachingStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customstaff.user',),
        ),
        migrations.CreateModel(
            name='TeachingStaffMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Sick Leave Available Days')),
                ('casualleave', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Casual Leave Available Days')),
                ('firstday', models.DateField(default=datetime.datetime(2020, 8, 11, 9, 16, 6, 464873, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customstaff.TeachingStaff')),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingStaffMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Sick Leave Available Days')),
                ('annualleave', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Annual Leave Available Days')),
                ('firstday', models.DateField(default=datetime.datetime(2020, 8, 11, 9, 16, 6, 465654, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customstaff.NonTeachingStaff')),
            ],
        ),
    ]
