# Generated by Django 3.0.8 on 2020-08-17 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0002_auto_20200817_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='leaveoversee',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 14, 15, 16, 687152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 14, 15, 16, 687122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 14, 15, 16, 685460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 14, 15, 16, 685994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='overseeing',
            field=models.ManyToManyField(related_name='overseeing', to='customstaff.NonTeachingStaff'),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorDetail', to='customstaff.Supervisor'),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 14, 15, 16, 684788, tzinfo=utc)),
        ),
    ]
