# Generated by Django 3.0.8 on 2020-08-12 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0003_auto_20200812_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 12, 1, 24, 800982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 12, 1, 24, 800959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 12, 1, 24, 800456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 12, 1, 24, 799659, tzinfo=utc)),
        ),
    ]
