# Generated by Django 3.0.8 on 2020-08-18 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0003_auto_20200817_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingstaffdetail',
            name='is_principal',
        ),
        migrations.RemoveField(
            model_name='teachingstaffdetail',
            name='is_viceprincipal',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 18, 6, 822322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 18, 6, 822296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 6, 820592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 6, 821151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 6, 819920, tzinfo=utc)),
        ),
    ]
