# Generated by Django 3.0.8 on 2020-08-18 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0004_auto_20200818_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstaffdetail',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Principal status'),
        ),
        migrations.AddField(
            model_name='teachingstaffdetail',
            name='is_viceprincipal',
            field=models.BooleanField(default=False, verbose_name='Viceprincipal status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nonteacher',
            field=models.BooleanField(default=False, verbose_name='Non teaching staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Principal status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='teacher status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_viceprincipal',
            field=models.BooleanField(default=False, verbose_name='Viceprincipal status'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 18, 50, 297395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 18, 50, 297362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 50, 294981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 50, 295850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 50, 294051, tzinfo=utc)),
        ),
    ]
