# Generated by Django 3.0.8 on 2020-08-13 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0006_auto_20200813_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 9, 37, 41, 901253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 9, 37, 41, 901229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 9, 37, 41, 900708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 9, 37, 41, 899920, tzinfo=utc)),
        ),
    ]
