# Generated by Django 3.0.8 on 2020-08-24 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0007_auto_20200824_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicePrincipal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customstaff.user',),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 644915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 644876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 641240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 642226, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 640614, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='VicePrincipalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Sick Leave Available Days')),
                ('annualleave', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Annual Leave Available Days')),
                ('firstday', models.DateField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 644060, tzinfo=utc))),
                ('is_teacher', models.BooleanField(default=True, verbose_name='teacher status')),
                ('is_viceprincipal', models.BooleanField(default=True, verbose_name='VicePrincipal status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VicePrincipalDetail', to='customstaff.VicePrincipal')),
            ],
        ),
    ]
