# Generated by Django 3.0.8 on 2020-08-24 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0008_auto_20200824_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='is_nonteacher',
            field=models.BooleanField(default=False, verbose_name='Non teaching staff status'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Principal status'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor status'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='teacher status'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_viceprincipal',
            field=models.BooleanField(default=False, verbose_name='Viceprincipal status'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 43, 32, 400214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 43, 32, 400181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 43, 32, 397173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 43, 32, 398024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 43, 32, 396102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 43, 32, 399524, tzinfo=utc)),
        ),
    ]
