# Generated by Django 3.0.8 on 2020-08-13 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0008_auto_20200813_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 50, 22, 920561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 50, 22, 920537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 13, 50, 22, 920015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 13, 50, 22, 919227, tzinfo=utc)),
        ),
    ]
