# Generated by Django 3.0.8 on 2020-08-24 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0009_auto_20200824_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_nonteacher',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_principal',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_viceprincipal',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 54, 55, 309844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 54, 55, 309817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 54, 55, 307573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 54, 55, 308103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 54, 55, 306914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 54, 55, 309291, tzinfo=utc)),
        ),
    ]
