# Generated by Django 3.0.8 on 2020-08-14 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0010_auto_20200813_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 8, 23, 14, 298013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 8, 23, 14, 297990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 8, 23, 14, 297583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 8, 23, 14, 296822, tzinfo=utc)),
        ),
    ]
