# Generated by Django 3.0.8 on 2020-08-25 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0012_auto_20200825_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 97685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 97789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 97764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 94477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 95006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 93831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 96132, tzinfo=utc)),
        ),
    ]
