# Generated by Django 3.0.8 on 2020-08-14 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0014_auto_20200814_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 9, 38, 36, 936408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='finalcomment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='firstcomment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 9, 38, 36, 936385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 9, 38, 36, 935875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffmore',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 9, 38, 36, 935066, tzinfo=utc)),
        ),
    ]
