# Generated by Django 3.0.8 on 2020-08-28 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0018_auto_20200828_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaffdetail',
            name='compensatedleave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Compensated Leave Available Days'),
        ),
        migrations.AddField(
            model_name='nonteachingstaffdetail',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 159415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 159432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 159372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 159394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 156126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 156676, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 155485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 157794, tzinfo=utc)),
        ),
    ]
