# Generated by Django 3.0.8 on 2020-09-01 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0025_auto_20200830_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 81621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 9, 1, 8, 55, 5, 81640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='finalcomment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='finalstatus',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Denied', 'denied')], default='Pending', max_length=10, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='firstcomment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='firststatus',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Denied', 'denied')], default='Pending', max_length=10, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='nonteachertimeofftype',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Official Leave', 'Official Leave'), ('Annual Leave', 'Annual Leave'), ('Over Time', 'Over Time'), ('Special Tuberculosis Leave', 'Special Tuberculosis Leave'), ('Maternal Leave', 'Maternal Leave'), ('Paternity Leave', 'Paternity Leave'), ('Jurors or Witnesses', 'Jurors or Witnesses'), ('Others', 'Others')], default='Sick Leave', max_length=100, verbose_name='Type of Leave'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='secondcomment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='secondstatus',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Denied', 'denied')], default='Pending', max_length=10, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 81573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 9, 1, 8, 55, 5, 81595, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 78334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 78865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 77758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 79997, tzinfo=utc)),
        ),
    ]
