# Generated by Django 3.0.8 on 2020-09-08 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0033_auto_20200907_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='totalhr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000, verbose_name='Total Hours'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000, verbose_name='Total Days'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 311586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 311607, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 311532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 311561, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 307336, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 307893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 306725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 56, 28, 309087, tzinfo=utc)),
        ),
    ]
