# Generated by Django 3.0.8 on 2020-09-09 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0034_auto_20200908_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaffdetail',
            name='increment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='supervisordetail',
            name='increment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='teachingstaffdetail',
            name='increment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='viceprincipaldetail',
            name='increment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000, verbose_name='Total Days'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 569706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 569724, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 569663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 569685, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 566397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 566939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 565785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 568061, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='IncrementAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 12, 16, 11, 571426, tzinfo=utc))),
                ('added', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
