# Generated by Django 3.0.8 on 2020-09-10 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0038_auto_20200909_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaffdetail',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='Secretary status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='Secretary status'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 439958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 438161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 438180, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 438112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 438135, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 434633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 435233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 433984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 436440, tzinfo=utc)),
        ),
    ]
