# Generated by Django 3.0.8 on 2020-10-08 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0049_auto_20201007_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='attachmentreceived',
            field=models.BooleanField(default=False, verbose_name='Attachment status'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 665799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 663364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 663387, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='nonteacherchangetimeofftype',
            field=models.CharField(blank=True, choices=[('Annual Leave', 'Annual Leave'), ('Over Time', 'Over Time'), ('No Pay Leave', 'No Pay Leave')], max_length=100, null=True, verbose_name='Change Leave Type'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 663308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 663337, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='teacherchangetimeofftype',
            field=models.CharField(blank=True, choices=[('Over Time', 'Casual Leave'), ('No Pay Leave', 'No Pay Leave')], max_length=100, null=True, verbose_name='Change Leave Type'),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 658996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 659734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 658172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 661292, tzinfo=utc)),
        ),
    ]
