# Generated by Django 3.0.8 on 2020-10-08 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0050_auto_20201008_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='attachmentrequired',
            field=models.BooleanField(default=False, verbose_name='Attachment Required'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 434313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='attachmentreceived',
            field=models.BooleanField(default=False, verbose_name='Attachment Received'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 432308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 432327, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 432261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 432286, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 428561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 429151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 427918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 53, 22, 430433, tzinfo=utc)),
        ),
    ]
