# Generated by Django 3.0.8 on 2020-11-03 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0073_auto_20201030_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='emergencytype',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Annual Leave', 'Annual Leave'), ('Casual Leave', 'Casual Leave')], default='Sick Leave', max_length=100, verbose_name='Type of Leave'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 137346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 134437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 134454, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 134394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 134416, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 130794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 131480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 130147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 132647, tzinfo=utc)),
        ),
    ]
