# Generated by Django 3.0.8 on 2020-11-03 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0074_auto_20201103_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='alltimeofftype',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Official Leave (In School)', 'Official Leave (In School)'), ('Official Leave (Outside)', 'Official Leave (Outside)'), ('Annual Leave', 'Annual Leave'), ('Casual Leave', 'Casual Leave'), ('Over Time', 'Over Time'), ('Special Tuberculosis Leave', 'Special Tuberculosis Leave'), ('Maternal Leave', 'Maternal Leave'), ('No-Pay Leave', 'No-Pay Leave'), ('Paternity Leave', 'Paternity Leave'), ('Study Leave', 'Study Leave'), ('Jurors or Witnesses', 'Jurors or Witnesses'), ('Leave for Special Events', 'Leave for Special Events'), ('Others', 'Others')], default='Sick Leave', max_length=100, verbose_name='All Type of Leave'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 829503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 826495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 826512, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 826451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 826473, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 822891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 823570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 822231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 824731, tzinfo=utc)),
        ),
    ]
