# Generated by Django 3.0.8 on 2020-11-04 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0075_auto_20201103_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='officialtype',
            field=models.CharField(choices=[('Official Leave (In School)', 'Official Leave (In School)'), ('Official Leave (Outside)', 'Official Leave (Outside)')], default='Official Leave (In School)', max_length=100, verbose_name='Type of Leave'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 385934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 383074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 383092, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 383027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 383049, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 379445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 380114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 378803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 381278, tzinfo=utc)),
        ),
    ]
