# Generated by Django 3.0.8 on 2020-11-08 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0077_auto_20201108_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaffdetail',
            name='sickleavecounter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100, verbose_name='Sick Leave Counter'),
        ),
        migrations.AddField(
            model_name='supervisordetail',
            name='sickleavecounter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100, verbose_name='Sick Leave Counter'),
        ),
        migrations.AddField(
            model_name='teachingstaffdetail',
            name='sickleavecounter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100, verbose_name='Sick Leave Counter'),
        ),
        migrations.AddField(
            model_name='viceprincipaldetail',
            name='sickleavecounter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100, verbose_name='Sick Leave Counter'),
        ),
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 278856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 275929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 275948, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 275872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 275907, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 272201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 272910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 271524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 8, 12, 58, 274128, tzinfo=utc)),
        ),
    ]
