# Generated by Django 3.0.8 on 2020-08-08 05:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('officialleave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('casualleave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('startdate', models.DateField(default=datetime.datetime(2020, 8, 8, 5, 11, 18, 133772, tzinfo=utc))),
                ('enddate', models.DateField(default=datetime.datetime(2020, 8, 8, 5, 11, 18, 133872, tzinfo=utc))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickleave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('officialleave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('annualleave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
