# Generated by Django 3.0.8 on 2020-08-08 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200808_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='timeofftype',
        ),
        migrations.AlterField(
            model_name='apply',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 31, 15, 661235, tzinfo=utc)),
        ),
    ]
