# Generated by Django 3.0.8 on 2020-08-08 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200808_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='timeofftype',
            field=models.CharField(choices=[('SL', 'sick leave'), ('OL', 'official leave'), ('CL', 'casual leave'), ('AL', 'annual leave')], default='SL', max_length=10),
        ),
        migrations.AlterField(
            model_name='apply',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 39, 2, 510456, tzinfo=utc)),
        ),
    ]
