# Generated by Django 3.0.8 on 2020-08-08 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200808_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 50, 26, 392055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='apply',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 50, 26, 392024, tzinfo=utc)),
        ),
    ]
